//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VOB.Web.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Balances
    {
        public Balances()
        {
            this.BalancePeriodo = new HashSet<BalancePeriodo>();
        }
    
        public int IdBalance { get; set; }
        public int IdCliente { get; set; }
        public byte IdMoneda { get; set; }
        public byte IdTipoBalance { get; set; }
        public string FormatoMoneda { get; set; }
        public string Ejecutivo { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string UltimoUsuario { get; set; }
    
        public virtual ICollection<BalancePeriodo> BalancePeriodo { get; set; }
        public virtual Clientes Clientes { get; set; }
        public virtual Monedas Monedas { get; set; }
        public virtual TipoBalance TipoBalance { get; set; }
    }
}
