//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VOB.Web.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BalanceDetalle
    {
        public long Id { get; set; }
        public int IdPeriodo { get; set; }
        public int IdConcepto { get; set; }
        public int FechaCierre { get; set; }
        public double Monto { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Comentario { get; set; }
        public string UltimoUsuario { get; set; }
    
        public virtual BalancePeriodo BalancePeriodo { get; set; }
    }
}
