//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VOB.Web.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        public Clientes()
        {
            this.Balances = new HashSet<Balances>();
        }
    
        public int IdCliente { get; set; }
        public Nullable<int> IdClienteBanco { get; set; }
        public string RUTCliente { get; set; }
        public string NombreCompleto { get; set; }
        public string RazonSocial { get; set; }
        public string Ejecutivo { get; set; }
        public string Giro { get; set; }
        public Nullable<int> CodActivo { get; set; }
        public string Segmento { get; set; }
        public string CRD { get; set; }
        public string VE { get; set; }
        public Nullable<System.DateTime> ClienteDesde { get; set; }
        public string UltimoUsuario { get; set; }
    
        public virtual ICollection<Balances> Balances { get; set; }
    }
}
