//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VOB.Web.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conceptos
    {
        public int IdConcepto { get; set; }
        public byte IdTipoBalance { get; set; }
        public Nullable<int> IdInterno { get; set; }
        public byte IdTipoConcepto { get; set; }
        public Nullable<short> IdGrupo { get; set; }
        public string Concepto { get; set; }
        public string ConceptoFormato { get; set; }
    
        public virtual ConceptosGrupos ConceptosGrupos { get; set; }
        public virtual TipoBalance TipoBalance { get; set; }
        public virtual TipoConceptos TipoConceptos { get; set; }
    }
}
