//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VOB.Web.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConceptosGrupos
    {
        public ConceptosGrupos()
        {
            this.Conceptos = new HashSet<Conceptos>();
        }
    
        public short IdGrupo { get; set; }
        public Nullable<byte> IdTipoBalance { get; set; }
        public Nullable<short> IdTipoGrupo { get; set; }
        public string NombreSubGrupo { get; set; }
    
        public virtual ICollection<Conceptos> Conceptos { get; set; }
        public virtual TipoGrupos TipoGrupos { get; set; }
    }
}
