//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VOB.Web.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estados
    {
        public Estados()
        {
            this.BalancePeriodo = new HashSet<BalancePeriodo>();
        }
    
        public byte IdEstado { get; set; }
        public string Estado { get; set; }
    
        public virtual ICollection<BalancePeriodo> BalancePeriodo { get; set; }
    }
}
