//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VOB.Web.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monedas
    {
        public Monedas()
        {
            this.Balances = new HashSet<Balances>();
        }
    
        public byte IdMoneda { get; set; }
        public string Moneda { get; set; }
        public string Simbolo { get; set; }
    
        public virtual ICollection<Balances> Balances { get; set; }
    }
}
