//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VOB.Web.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoGrupos
    {
        public TipoGrupos()
        {
            this.ConceptosGrupos = new HashSet<ConceptosGrupos>();
        }
    
        public short IdTipoGrupo { get; set; }
        public string NombreTipoGrupo { get; set; }
    
        public virtual ICollection<ConceptosGrupos> ConceptosGrupos { get; set; }
    }
}
