//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VOB.Web.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoBalance
    {
        public TipoBalance()
        {
            this.Balances = new HashSet<Balances>();
            this.Conceptos = new HashSet<Conceptos>();
        }
    
        public byte IdTipoBalance { get; set; }
        public string TipoBalance1 { get; set; }
    
        public virtual ICollection<Balances> Balances { get; set; }
        public virtual ICollection<Conceptos> Conceptos { get; set; }
    }
}
